version: '3.8'

networks:
  waha-network:
    driver: bridge

services:
  waha:
    image: devlikeapro/waha
    ports:
      - "3000:3000"
    environment:
      - WAHA_PRINT_QR=false
      - TZ=America/Sao_Paulo
    networks:
      - waha-network

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./redisdb:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - waha-network

  fastapi:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./chromadb:/api/chromadb
    depends_on:
      - waha
      - redis
    networks:
      - waha-network

  webhook-config:
    image: curlimages/curl:latest
    volumes:
      - ./configure-webhook.sh:/configure-webhook.sh
    entrypoint: ["/bin/sh", "/configure-webhook.sh"]
    depends_on:
      - waha
      - fastapi
    networks:
      - waha-network

  streamlit:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8501:8501"
    volumes:
      - ./chromadb:/app/chromadb
    depends_on:
      - waha
      - redis
